import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  textRpgSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Developer Documentation',
      items: [{type: 'autogenerated', dirName: 'developer'}],
    },
    {
      type: 'category',
      label: 'Admin Guides',
      items: [{type: 'autogenerated', dirName: 'admin'}],
    },
  ],
};

export default sidebars;
