import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  homelabSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Hardware',
      items: [{type: 'autogenerated', dirName: 'hardware'}],
    },
    {
      type: 'category',
      label: 'Proxmox',
      items: [{type: 'autogenerated', dirName: 'proxmox'}],
    },
    {
      type: 'category',
      label: 'Kubernetes',
      items: [
        {
          type: 'category',
          label: 'K3s',
          items: [{type: 'autogenerated', dirName: 'k8s/k3s'}],
        },
        {
          type: 'category',
          label: 'RKE2',
          items: [{type: 'autogenerated', dirName: 'k8s/rke2'}],
        },
      ],
    },
  ],
};

export default sidebars;
