import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  gamingSidebar: [
    "intro",
    {
      type: "category",
      label: "Diablo IV",
      items: [{ type: "autogenerated", dirName: "diablo-iv" }],
    },
    {
      type: "category",
      label: "Turtle WoW",
      items: [{ type: "autogenerated", dirName: "turtle-wow" }],
    },
    {
      type: "category",
      label: "WoW Retail",
      items: [{ type: "autogenerated", dirName: "wow-retail" }],
    },
  ],
};

export default sidebars;
