apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: documentation-site
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-org/documentation-site
  ref:
    branch: main
  secretRef:
    name: github-credentials
