apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: documentation-site
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/documentation-site
      sourceRef:
        kind: GitRepository
        name: documentation-site
      interval: 1m
  # Values will be overridden by kustomization
  values: {}
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    recreate: true
    cleanupOnFail: true
