apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: documentation-site
  namespace: flux-system
spec:
  image: ghcr.io/your-org/documentation-site
  interval: 1m
  secretRef:
    name: github-registry-credentials
